### PR TITLE
Command chaining & cy.within()

### PR DESCRIPTION
**Pull request by badeball**
This patch adds the foundation for supporting chaining off of other commands, as well as support for using with `cy.within()`.

Beware, I am completely new to Cypress and have gathered most of my inspiration from this repository and [kentcdodds/cypress-testing-library](https://github.com/kentcdodds/cypress-testing-library).

### CODE REVIEW

**Comment by bahmutov** [comment]
@badeball can you take a look - I have merged your previous PR https://github.com/cypress-io/cypress-xpath/pull/35 so now this code needs to be updated a little

**Comment by badeball** [comment]
@bahmutov, I've fixed the failing tests with ba525e3. Turns our that I had somewhat misunderstood some assertions, which happened to work before 5afe28d was introduced.

**Comment by bahmutov** [comment]
@badeball this is so so good, thank you 👏

**Pull request merged**
